## Assignment 2

In [2]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt


import numpy as np
from scipy import stats

In [3]:
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [ 0.9, 0.1, 0 ], [ 0, 0.9, 0.1 ] ] ) ) 

b1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
b2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2

x_obs = (-0.2, 2.6, 1.3)
pX = np.array([b1.prob(x_obs), b2.prob(x_obs)])
print(pX/sum(pX))

[alfaHat, c] = mc.forward(pX/sum(pX))

print(f"alfaHat = {alfaHat}")
print(f"c = {c}")


[[0.8757894  0.06495786 0.55215885]
 [0.1242106  0.93504214 0.44784115]]
alfaHat = [[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
c = [0.8757894  0.15196629 0.45640399]


In [4]:
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [ 0.9, 0.1, 0 ], [ 0, 0.9, 0.1 ] ] ) ) 
g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[2], stdevs=[3] )   # Distribution for state = 2

x_obs = (-0.2, 2.6, 1.3)
h  = HMM( mc, [g1, g2])

c = h.logprob(x_obs)
print(c)



-2.728714016312506
