## Assigmnent 3

In [6]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt

import os
import numpy as np

### Feature extraction

In [58]:

acc = []

for filename in os.listdir('sensorlogger'):
    path = os.path.join('sensorlogger',filename)
    with open(path) as file:        
        if os.path.isfile(path):
            lines = [line.split() for line in file]
            # absolute value of norm of acceleration vector - gravity
            acc.append([ np.abs((np.sqrt(float(line[2])**2 + float(line[3])**2 + float(line[4])**2))-9.82) for line in lines ])

            
%matplotlib qt
plt.figure(figsize= (15,5))
plt.plot(acc[0])
plt.title("Magnitude of l2 Norm of Acceleration (Gravity Subtracted)")
plt.xlabel("Sample")
plt.ylabel("Amplitude")

plt.show()

qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [135]:

"""Windowing"""
wLen = 100 # window length (samples)
overlap = 0 # is 
windows = []

step = wLen-overlap

X = []
for rec in acc:
    x = []
    for n in range(0,len(rec)-wLen +1,step):
        x.append( sum(rec[n:n+wLen])/wLen )
    
    """divide recordings into chunks of 50 windows"""
    #####
    for chunk in x:
        nchunks = len(x)//50
        if nchunks:
            chunks = [x[n:n+50] for n in range(nchunks)]
        X.extend(chunks)
    #####
    
#print(np.shape(X))
    #X.append(x)
print(len(X[0]))
    
plt.figure(figsize= (15,5))
plt.plot(X[0])
plt.title("Means of Segments of Acceleration")
plt.xlabel("Window")
plt.ylabel("Amplitude")

plt.show()


50


qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [131]:
"""Cluster training data into N separate categories, for estimation of output probabilities"""
data1 = [] 
data2 = []
data3 = []

"""Automatic labeling"""
S = [] # labels
for rec in X:
    s = []
    for a in rec:
        if a > 3.5:
            s.append(3) #running
            data3.append(a)
        elif a > 0.6:
            s.append(2)  #walking
            data2.append(a)
        else:
            s.append(1)  #standing
            data1.append(a)
    S.append(s)  
        
colors = {1: 'red', 2: 'green', 3: 'blue'}

plt.figure(figsize= (15,5))
plt.plot([t2 for t2 in range(0, len(X[0]))], X[0])
for i, val in enumerate(S[0]):
    plt.scatter(i, val, c = colors[val])
for key in colors: 
    plt.scatter([],[], c=colors[key], label = f'S = {key}')
    
plt.legend()
    
plt.legend()
plt.title("Labeled Segments")
plt.xlabel("Window")
plt.ylabel("Amplitude")

plt.show()

qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [132]:
"""All plots"""

plt.figure(figsize= (15,10))

plt.subplot(311)
plt.plot(acc[0])

plt.subplot(312)
plt.plot(X[0])

plt.subplot(313)
plt.plot([t2 for t2 in range(0, len(X[0]))], X[0])
for i, val in enumerate(S[0]):
    plt.scatter(i, val, color = colors[val])

plt.show()



qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [137]:

fig, (ax1,ax2,ax3) = plt.subplots(3)

ax1.hist(data1, bins = 30)
ax2.hist(data2, bins = 30)
ax3.hist(data3, bins = 30)
plt.show()


qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [138]:
plt.hist(data2, bins = 30)
plt.title("Feature Sample Amplitudes")
plt.xlabel("Amplitude")
plt.ylabel("Count")
plt.show()

qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


## Train/Test Split

In [ ]:

from sklearn.model_selection import train_test_split




In [6]:
"""Extracting data to csv"""

datapoints = np.array([X,S], dtype = object).T

import csv

with open('features.csv', 'w') as csvfile:
    Writer = csv.writer(csvfile)
    for data in datapoints:
        Writer.writerow(data)


In [139]:
"""Initialization"""

"""Infinite ergodic HMM may start in any state. Assumption here is that
    each state is equally likely to occur as initial state"""

A = np.array( [ [0.9, 0.09, 0.01],
             [0.05, 0.9, 0.05],
             [0.01, 0.09, 0.9] ])

mc = MarkovChain( np.full( (1,3),1/3 ) , A )

"""The diagonal elements of the transition matrix can be chosen to indicate 
    approximately the average state durations. Here I assume that each state duration is equally long"""


"""Output probability distributions must be initialized differently for each state"""
# Maybe do this with separate data?

from scipy.stats import norm
        
mu1, std1 = norm.fit(data1) #standing
mu2, std2 = norm.fit(data2) #walking
mu3, std3 = norm.fit(data3) #running


# Looks reasonable
print(mu1,std1)
print(mu2,std2)
print(mu3,std3)


b1 = GaussD( means=[mu1], stdevs=[std1] )   # Distribution for state = standing
b2 = GaussD( means=[mu2], stdevs=[std2] )   # Distribution for state = walking
b3 = GaussD( means=[mu3], stdevs=[std3] )   # Distribution for state = running

"""Initial HMM"""

h0  = HMM( mc, [b1, b2, b3])

0.2087852238707523 0.1314614876094346
1.8582047313753747 0.49280747109148304
6.148375731454781 1.0581921704146957


### Training

In [140]:
"""Updating initial probability vector, and transition probabilities"""

epsilon = 10e-10

gma = []
xi = []
# for x in training data
for x_obs in X:
    pX = np.array([b1.prob(x_obs), b2.prob(x_obs), b3.prob(x_obs)])
    xi_r = np.zeros( (3,3,len(x_obs)) )

    # replace zero probabilities with some small probability epsilon
    with np.nditer(pX, op_flags =['readwrite']) as it:
        for x in it:
            x[...] = max(x,epsilon)

    """normalize"""
    pX = pX / np.sum(pX,axis=0)

    """Scaling?"""
    #sf = [np.max(p) for p in pX.T]
    #pX = pX/sf

    [alfaHat, c] = mc.forward(pX)
    betaHat = mc.backward(pX, c)
    
    tmp = np.multiply(alfaHat, betaHat)
    gma_r = np.multiply(tmp,c) # gamma i,t
    gma.append(gma_r)
    
    """xi"""
    for t in range(len(x_obs)-1):
        for i in range(3):
            for j in range(3):
                xi_r[i,j,t] = alfaHat[i,t]*A[i,j]*pX[j,t+1]*betaHat[j,t+1]
        
    xi.append(np.sum(xi_r[:,:,:-1], axis = 2))
    
xi = np.sum( np.array(xi), axis= 0)

"""Update equation"""
q_new = np.zeros((1,3))
for r in gma:
    q_new = q_new + r[:,0]
    
q_new = q_new/len(gma)
a_new = xi/(np.sum(xi,axis=1)[:,None])

print(f"q_new: {q_new}\n")
print(f"a_new:\n {a_new}\n")

#print(np.sum(a_new,axis = 1)) # should add up to 1

q_new: [[0.14670588 0.5389324  0.31436172]]

a_new:
 [[8.57777771e-01 1.37855673e-01 4.36655604e-03]
 [3.71315245e-02 8.98729711e-01 6.41387642e-02]
 [9.02931699e-09 4.32473497e-02 9.56752641e-01]]

