## Assignment 2

In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt


import numpy as np
from scipy import stats

In [18]:
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [ 0.9, 0.1, 0 ], [ 0, 0.9, 0.1 ] ] ) ) 

b1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
b2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2

x_obs = [-0.2, 2.6, 1.3]
pX = np.array([b1.prob(x_obs), b2.prob(x_obs)])

""" assuming you applied forward directly to the scaled probabilities produced
by prob. """

""" it is likely that your implementation of the Forward Algorithm is correct, but
that you are applying it to the true, unscaled probabilities by accounting
for the scaling factors(?) already before running forward"""

[alfaHat, c] = mc.forward(pX) ### Needs scaling?
#print(pX)
#print(np.sum(pX))

print(f"alfaHat = {alfaHat}\n")
print(f"c = {c}\n")


[[0.8757894  0.06495786 0.55215885]
 [0.1242106  0.93504214 0.44784115]]
alfaHat = [[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]

c = [0.39104269 0.03177681 0.14165001 0.05811253]



In [10]:
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [ 0.9, 0.1, 0 ], [ 0, 0.9, 0.1 ] ] ) ) 
g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[2], stdevs=[3] )   # Distribution for state = 2

x_obs = (-0.2, 2.6, 1.3)
h  = HMM( mc, [g1, g2])

c = h.logprob(x_obs)
print(c)



-5.784944928633746


## A.3.2

In [20]:
mc = MarkovChain( np.array( [ 1, 0 ] ), np.array( [ [ 0.9, 0.1, 0 ], [ 0, 0.9, 0.1 ] ] ) ) 

b1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
b2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2

x_obs = (-0.2, 2.6, 1.3)
pX = np.array([b1.prob(x_obs), b2.prob(x_obs)])
    
[alfaHat, c] = mc.forward(pX)

betaHat = mc.backward(pX, np.array([1, 0.1625, 0.8266, 0.0581])) ### Needs scaling

print(f"betaHat: {betaHat}")


"""These numerical results require that all calculations use the scaled state-
conditional probability values pX as supplied by the OutputDistr prob-
method (try help GaussD/prob for more information). If you used the accompanying scale factors(?) from prob to undo the scaling before calling
backward, you may get different results"""

betaHat: [[0.03351751 0.17810097 0.        ]
 [0.28206259 1.60290875 2.08222888]]


'These numerical results require that all calculations use the scaled state-\nconditional probability values pX as supplied by the OutputDistr prob-\nmethod (try help GaussD/prob for more information). If you used the accompanying scale factors (?) from prob to undo the scaling before calling\nbackward, you may get different results'