## Assigmnent 3

In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt

import os
import numpy as np

### Feature extraction

In [2]:

acc = []

for filename in os.listdir('sensorlogger'):
    path = os.path.join('sensorlogger',filename)
    with open(path) as file:        
        if os.path.isfile(path):
            lines = [line.split() for line in file]
            # absolute value of norm of acceleration vector - gravity
            acc.append([ np.abs((np.sqrt(float(line[2])**2 + float(line[3])**2 + float(line[4])**2))-9.82) for line in lines ])

            
%matplotlib qt
plt.figure(figsize= (15,5))
plt.plot(acc[0])
plt.title("Magnitude of l2 Norm of Acceleration (Gravity Subtracted)")
plt.xlabel("Sample")
plt.ylabel("Amplitude")

plt.show()

/nix/store/b2hc0i92l22ir2kavnjn3z5z6mzabbvm-glibc-2.34-210/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/6j6hl9x71gpq4siar7ns8w2fwx0s7d6q-gvfs-1.52.2/lib/gio/modules/libgvfsdbus.so)
Failed to load module: /nix/store/6j6hl9x71gpq4siar7ns8w2fwx0s7d6q-gvfs-1.52.2/lib/gio/modules/libgvfsdbus.so
QApplication: invalid style override 'gtk2' passed, ignoring it.
	Available styles: bb10dark, bb10bright, cleanlooks, gtk2, cde, motif, plastique, Windows, Fusion
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBuff

In [3]:

"""Windowing"""
wLen = 100 # window length (samples)
overlap = 0 # is 
windows = []

step = wLen-overlap

X = []

count = 0
for rec in acc:
    x = []
    for n in range(0,len(rec)-wLen +1,step):
        x.append( sum(rec[n:n+wLen])/wLen )
    
    """divide recordings into chunks of 50 windows"""
    #####
    nchunks = len(x)//50
    chunks = [x[n:n+50] for n in range(0, len(x), 50)]    
    if len(chunks[-1]) <40 and len(x)>= 50:
        chunks[-2].extend(chunks[-1])
        chunks = chunks[:-1]        
    X.extend(chunks)
    count = count + nchunks+1 
    #####
    
#print(np.shape(X))
    #X.append(x)
#print(len(X[0]))
#print(count)

plt.figure(figsize= (15,5))
plt.plot(X[0])
plt.title("Means of Segments of Acceleration")
plt.xlabel("Window")
plt.ylabel("Amplitude")

plt.show()


qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [4]:
"""Cluster training data into N separate categories, for estimation of output probabilities"""
data1 = [] 
data2 = []
data3 = []

"""Automatic labeling"""
S = [] # labels
for rec in X:
    s = []
    for a in rec:
        if a > 3.5:
            s.append(3) #running
            data3.append(a)
        elif a > 0.6:
            s.append(2)  #walking
            data2.append(a)
        else:
            s.append(1)  #standing
            data1.append(a)
    S.append(s)  
        
colors = {1: 'red', 2: 'green', 3: 'blue'}

plt.figure(figsize= (15,5))
plt.plot([t2 for t2 in range(0, len(X[0]))], X[0])
for i, val in enumerate(S[0]):
    plt.scatter(i, val, c = colors[val])
for key in colors: 
    plt.scatter([],[], c=colors[key], label = f'S = {key}')
    
plt.legend()
    
plt.legend()
plt.title("Labeled Segments")
plt.xlabel("Window")
plt.ylabel("Amplitude")

plt.show()

qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [5]:
"""All plots"""

plt.figure(figsize= (15,10))

plt.subplot(311)
plt.plot(acc[0])

plt.subplot(312)
plt.plot(X[0])

plt.subplot(313)
plt.plot([t2 for t2 in range(0, len(X[0]))], X[0])
for i, val in enumerate(S[0]):
    plt.scatter(i, val, color = colors[val])

plt.show()



qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [6]:

fig, (ax1,ax2,ax3) = plt.subplots(3)

ax1.hist(data1, bins = 30)
ax2.hist(data2, bins = 30)
ax3.hist(data3, bins = 30)
plt.show()


qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.


In [7]:
plt.hist(data2, bins = 30)
plt.title("Feature Sample Amplitudes")
plt.xlabel("Amplitude")
plt.ylabel("Count")
plt.show()

## Train/Test Split

In [8]:

from sklearn.model_selection import train_test_split

datapoints = np.array([X,S], dtype = object).T

X_train, X_test, y_train, y_test = train_test_split( X,S, test_size = 0.33, random_state = 1)


In [9]:
"""Exporting data to csv"""

datapoints = np.array([X,S], dtype = object).T

import csv

with open('features.csv', 'w') as csvfile:
    Writer = csv.writer(csvfile)
    for data in datapoints:
        Writer.writerow(data)


In [10]:
"""Initialization"""

"""Infinite ergodic HMM may start in any state. Assumption here is that
    each state is equally likely to occur as initial state"""

A = np.array( [ [0.9, 0.09, 0.01],
             [0.05, 0.9, 0.05],
             [0.01, 0.09, 0.9] ])

mc = MarkovChain( np.full( (1,3),1/3 ) , A )

"""The diagonal elements of the transition matrix can be chosen to indicate 
    approximately the average state durations. Here I assume that each state duration is equally long"""


"""Output probability distributions must be initialized differently for each state"""
# Maybe do this with separate data?

from scipy.stats import norm
        
mu1, std1 = norm.fit(data1) #standing
mu2, std2 = norm.fit(data2) #walking
mu3, std3 = norm.fit(data3) #running


# Looks reasonable
print(mu1,std1)
print(mu2,std2)
print(mu3,std3)


b1 = GaussD( means=[mu1], stdevs=[std1] )   # Distribution for state = standing
b2 = GaussD( means=[mu2], stdevs=[std2] )   # Distribution for state = walking
b3 = GaussD( means=[mu3], stdevs=[std3] )   # Distribution for state = running

"""Initial HMM"""

h0  = HMM( mc, [b1, b2, b3])

0.2149082219447096 0.12722765619672527
1.7420355493184476 0.45829907888362154
5.9660427944252 0.9862693139955239


### Training

In [11]:
"""Updating initial probability vector, and transition probabilities"""

epsilon = 10e-10

gma = []
xi = []
# for x in training data
for xr in X_train:
    pX = np.array([b1.prob(xr), b2.prob(xr), b3.prob(xr)])
    xi_r = np.zeros( (3,3,len(xr)) )

    # replace zero probabilities with some small probability epsilon
    with np.nditer(pX, op_flags =['readwrite']) as it:
        for x in it:
            x[...] = max(x,epsilon)

    """normalize"""
    pX = pX / np.sum(pX,axis=0)

    """Scaling?"""
    #sf = [np.max(p) for p in pX.T]
    #pX = pX/sf

    [alfaHat, c] = mc.forward(pX)
    betaHat = mc.backward(pX, c)
    
    tmp = np.multiply(alfaHat, betaHat)
    gma_r = np.multiply(tmp,c) # gamma i,t
    gma.append(gma_r)
    
    """xi"""
    for t in range(len(xr)-1):
        for i in range(3):
            for j in range(3):
                xi_r[i,j,t] = alfaHat[i,t]*A[i,j]*pX[j,t+1]*betaHat[j,t+1]
        
    xi.append(np.sum(xi_r[:,:,:-1], axis = 2))
    
xi = np.sum( np.array(xi), axis= 0)

"""Update equation"""
q_new = np.zeros((1,3))
for r in gma:
    q_new = q_new + r[:,0]
    
q_new = q_new/len(gma)
a_new = xi/(np.sum(xi,axis=1)[:,None])

print(f"q_new: {q_new}\n")
print(f"a_new:\n {a_new}\n")

#print(np.sum(a_new,axis = 1)) # should add up to 1

q_new: [[0.14401977 0.4299986  0.42598163]]

a_new:
 [[8.63657959e-01 1.25575616e-01 1.07664244e-02]
 [3.69473118e-02 9.18028675e-01 4.50240135e-02]
 [7.22775881e-07 5.66487625e-02 9.43350515e-01]]



In [15]:
h0.train(X_train)

print(h0.stateGen.q)
print(h0.stateGen.A)

[[0.14330802 0.43037157 0.42632042]]
[[8.63729894e-01 1.25624871e-01 1.06452349e-02]
 [3.67157940e-02 9.18247011e-01 4.50371947e-02]
 [2.15533475e-18 5.66390967e-02 9.43360903e-01]]


## Evaluation